sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.8
  - 2.6.4
gemfile:
  - gemfiles/sidekiq_3.3.1.gemfile
  - gemfiles/sidekiq_3.x.gemfile
  - gemfiles/sidekiq_4.x.gemfile
  - gemfiles/sidekiq_5.x.gemfile
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
notifications:
  email: false

cache: bundler
before_install: gem install bundler -v 1.16.5
after_success: bundle exec codeclimate-test-reporter
script: bundle exec rake spec
