language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
notifications:
  email: false

gemfile:
  - gemfiles/sidekiq_3.3.1.gemfile
  - gemfiles/sidekiq_3.x.gemfile
  - gemfiles/sidekiq_4.x.gemfile
  - gemfiles/sidekiq_5.x.gemfile
  - gemfiles/sidekiq_6.x.gemfile

matrix:
  include:
    - rvm: "2.6.5"
      gemfile: "gemfiles/sidekiq_5.x.gemfile"
      env:
        - CODECLIMATE_REPORT=true
  exclude:
    - rvm: "2.3.8"
      gemfile: "gemfiles/sidekiq_6.x.gemfile"
    - rvm: "2.4.9"
      gemfile: "gemfiles/sidekiq_6.x.gemfile"

cache:
  directories:
    - ./vendor

env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN

before_install:
  - gem install bundler -v '~> 2.1'

before_script:
  - if [ ! -f ./vendor/cc-test-reporter ]; then
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./vendor/cc-test-reporter;
    chmod +x ./vendor/cc-test-reporter;
    fi
  - if [ ! -z "$CODECLIMATE_REPORT" ]; then
    echo "Start recording Codeclimate test coverage";
    ./vendor/cc-test-reporter before-build;
    fi
script:
  - bundle exec rake spec
after_success:
  - if [ ! -z "$CODECLIMATE_REPORT" ]; then
    echo "Finish recording Codeclimate test coverage";
    ./vendor/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
    fi
